# Generated by Django 3.0.5 on 2020-04-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('Available', 'item ready to be purchased'), ('sold', 'item sold'), ('restocking', 'item restocking in few days')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('Available', 'item ready to be purchased'), ('sold', 'item sold'), ('restocking', 'item restocking in few days')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('Available', 'item ready to be purchased'), ('sold', 'item sold'), ('restocking', 'item restocking in few days')], default='SOLD', max_length=10),
        ),
    ]
